version: '3'
services:
    alert-service: 
        build:
            context: .
            dockerfile: ./alert-service/Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
            - .env
        networks:
            - child-safety-network
        ports:
            - 3000:3000
    car-registration-service: 
        build:
            context: .
            dockerfile: ./car-registration-service/Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
            - .env
        networks:
            - child-safety-network
    phone-pair-service: 
        build:
            context: .
            dockerfile: ./phone-pair-service/Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
            - .env
        networks:
            - child-safety-network
    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - db-data:/data/db
        ports:
            - "27017:27017"
        networks:
            - child-safety-network
    nginx:
        image: nginx:1.13-alpine
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - alert-service
            - car-registration-service
            - phone-pair-service
        networks:
            - child-safety-network

volumes:
    db-data:

networks:
    child-safety-network: